In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [ ]:
# prompt: i want to create program to iterate the total number of column in the df

# create a sample dataframe
data = {'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}
df = pd.DataFrame(data)

# iterate over the total number of columns
for i in range(df.shape[1]):
  print(f"Column index: {i}, Column name: {df.columns[i]}")

In [ ]:
df=pd.read_csv('/content/bank.csv')
df

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [ ]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='object')

In [ ]:
df.describe()
print(df['deposit'].value_counts())

deposit
0    5873
1    5289
Name: count, dtype: int64


In [ ]:
for col in df.columns:
  print(f"{col}")
  print(df[col].unique())
  print("___"*50)


age
[59 56 41 55 54 42 60 37 28 38 30 29 46 31 35 32 49 43 26 40 33 23 48 45
 36 52 53 39 57 51 44 24 50 27 34 47 25 58 61 68 75 22 69 66 85 72 90 67
 71 21 74 65 62 83 70 76 77 19 73 63 20 78 95 64 79 82 18 86 84 87 92 81
 80 93 88 89]
______________________________________________________________________________________________________________________________________________________
job
['admin.' 'technician' 'services' 'management' 'retired' 'blue-collar'
 'unemployed' 'entrepreneur' 'housemaid' 'unknown' 'self-employed'
 'student']
______________________________________________________________________________________________________________________________________________________
marital
['married' 'single' 'divorced']
______________________________________________________________________________________________________________________________________________________
education
['secondary' 'tertiary' 'primary' 'unknown']
_____________________________________________________________

In [ ]:
from sklearn.preprocessing import LabelEncoder
for col in df.columns:
  if df[col].dtype=="object":
    le=LabelEncoder()
    df[col]=le.fit_transform(df[col])

In [ ]:
for col in df.columns:
  print(f"{col}")
  print(df[col].unique())
  print("___"*50)


age
[59 56 41 55 54 42 60 37 28 38 30 29 46 31 35 32 49 43 26 40 33 23 48 45
 36 52 53 39 57 51 44 24 50 27 34 47 25 58 61 68 75 22 69 66 85 72 90 67
 71 21 74 65 62 83 70 76 77 19 73 63 20 78 95 64 79 82 18 86 84 87 92 81
 80 93 88 89]
______________________________________________________________________________________________________________________________________________________
job
[ 0  9  7  4  5  1 10  2  3 11  6  8]
______________________________________________________________________________________________________________________________________________________
marital
[1 2 0]
______________________________________________________________________________________________________________________________________________________
education
[1 2 0 3]
______________________________________________________________________________________________________________________________________________________
default
[0 1]
___________________________________________________________________

In [ ]:
print(df.corr()['deposit'])

age          0.034901
job          0.063395
marital      0.067610
education    0.095948
default     -0.040680
balance      0.081129
housing     -0.203888
loan        -0.110580
contact     -0.249847
day         -0.056326
month       -0.037121
duration     0.451919
campaign    -0.128081
pdays        0.151593
previous     0.139867
poutcome    -0.122369
deposit      1.000000
Name: deposit, dtype: float64


In [ ]:
x= df.drop('deposit',axis=1)
y=df['deposit']
print(x)

       age  job  marital  education  default  balance  housing  loan  contact  \
0       59    0        1          1        0     2343        1     0        2   
1       56    0        1          1        0       45        0     0        2   
2       41    9        1          1        0     1270        1     0        2   
3       55    7        1          1        0     2476        1     0        2   
4       54    0        1          2        0      184        0     0        2   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
11157   33    1        2          0        0        1        1     0        0   
11158   39    7        1          1        0      733        0     0        2   
11159   32    9        2          1        0       29        0     0        0   
11160   43    9        1          1        0        0        0     1        0   
11161   34    9        1          1        0        0        0     0        0   

       day  month  duration

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.1,random_state=60)
model= LogisticRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.8173679498657117


In [ ]:
params={
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear'],
    'class_weight': [None, 'balanced']
}

In [ ]:
from sklearn.model_selection import GridSearchCV
grid_search=GridSearchCV(LogisticRegression(max_iter=1000),params,cv=3,scoring='accuracy')
grid_search.fit(x_train,y_train)
bestparm=grid_search.best_params_
best_model=grid_search.best_estimator_
y_pred=best_model.predict(x_test)
print(accuracy_score(y_test,y_pred))

0.8245299910474485


In [ ]:
import statsmodels.api as sm
X_const = sm.add_constant(x)
model = sm.Logit(y, X_const).fit()
print(model.summary())


Optimization terminated successfully.
         Current function value: 0.468294
         Iterations 7
                           Logit Regression Results                           
Dep. Variable:                deposit   No. Observations:                11162
Model:                          Logit   Df Residuals:                    11145
Method:                           MLE   Df Model:                           16
Date:                Sat, 24 May 2025   Pseudo R-squ.:                  0.3231
Time:                        11:59:38   Log-Likelihood:                -5227.1
converged:                       True   LL-Null:                       -7721.6
Covariance Type:            nonrobust   LLR p-value:                     0.000
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0527      0.025     -2.066      0.039      -0.103      -0.003
x1             0.0916      0.

In [ ]:
x= df.drop('deposit',axis=1)
y=df['deposit']
print(x)

       age  job  marital  education  default  balance  housing  loan  contact  \
0       59    0        1          1        0     2343        1     0        2   
1       56    0        1          1        0       45        0     0        2   
2       41    9        1          1        0     1270        1     0        2   
3       55    7        1          1        0     2476        1     0        2   
4       54    0        1          2        0      184        0     0        2   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
11157   33    1        2          0        0        1        1     0        0   
11158   39    7        1          1        0      733        0     0        2   
11159   32    9        2          1        0       29        0     0        0   
11160   43    9        1          1        0        0        0     1        0   
11161   34    9        1          1        0        0        0     0        0   

       day  month  duration

In [ ]:
x_featured1= x.drop(['job','default'],axis =1)

In [ ]:
x_featured1

age  marital  education  balance  housing  loan  contact  day  month  \
0       59        1          1     2343        1     0        2    5      8   
1       56        1          1       45        0     0        2    5      8   
2       41        1          1     1270        1     0        2    5      8   
3       55        1          1     2476        1     0        2    5      8   
4       54        1          2      184        0     0        2    5      8   
...    ...      ...        ...      ...      ...   ...      ...  ...    ...   
11157   33        2          0        1        1     0        0   20      0   
11158   39        1          1      733        0     0        2   16      6   
11159   32        2          1       29        0     0        0   19      1   
11160   43        1          1        0        0     1        0    8      8   
11161   34        1          1        0        0     0        0    9      5   

       duration  campaign  pdays  previous  poutcome  
0          1042         1     -1         0         3  
1          1467         1     -1         0         3  
2          1389         1     -1         0         3  
3           579         1     -1         0         3  
4           673         2     -1         0         3  
...         ...       ...    ...       ...       ...  
11157       257         1     -1         0         3  
11158        83         4     -1         0         3  
11159       156         2     -1         0         3  
11160         9         2    172         5         0  
11161       628         1     -1         0         3  

[11162 rows x 14 columns]

In [ ]:
x_featured1Scaled=sc.fit_transform(x_featured1)
print(x_featured1Scaled)

[[ 1.49150488 -0.31867191 -0.38050056 ... -0.48118405 -0.36325984
   0.52070456]
 [ 1.23967567 -0.31867191 -0.38050056 ... -0.48118405 -0.36325984
   0.52070456]
 [-0.0194704  -0.31867191 -0.38050056 ... -0.48118405 -0.36325984
   0.52070456]
 ...
 [-0.77495804  1.27998692 -0.38050056 ... -0.48118405 -0.36325984
   0.52070456]
 [ 0.14841574 -0.31867191 -0.38050056 ...  1.10957066  1.81833188
  -2.47059976]
 [-0.6070719  -0.31867191 -0.38050056 ... -0.48118405 -0.36325984
   0.52070456]]


In [ ]:
x_train,x_test,y_train,y_test =train_test_split(x_featured1Scaled,y,test_size=0.1,random_state=60)
model1=LogisticRegression()
model1.fit(x_train,y_train)
y_pred=model1.predict(x_test)
print(accuracy_score(y_test,y_pred))

0.8164726947179947


In [ ]:
params={
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear'],
    'class_weight': [None, 'balanced']
}

In [ ]:
from sklearn.model_selection import GridSearchCV
grid_search=GridSearchCV(LogisticRegression(max_iter=1000),params,cv=3,scoring='accuracy')
grid_search.fit(x_train,y_train)
bestparm=grid_search.best_params_
best_model=grid_search.best_estimator_
y_pred=best_model.predict(x_test)
print(accuracy_score(y_test,y_pred))

0.8263205013428827


In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[509  94]
 [100 414]]


In [ ]:
print("Train Accuracy:", model1.score(x_train, y_train))
print("Test Accuracy:", model1.score(x_test, y_test))

Train Accuracy: 0.7942259830761573
Test Accuracy: 0.8164726947179947


In [ ]:
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, classification_report, confusion_matrix
)

y_pred = model1.predict(x_test)


y_proba = model1.predict_proba(x_test)[:, 1]  # Use [:,1] for positive class

# Print metrics
print("✅ Accuracy     :", round(accuracy_score(y_test, y_pred), 4))
print("✅ Precision    :", round(precision_score(y_test, y_pred), 4))
print("✅ Recall       :", round(recall_score(y_test, y_pred), 4))
print("✅ F1 Score     :", round(f1_score(y_test, y_pred), 4))
print("✅ ROC AUC Score:", round(roc_auc_score(y_test, y_proba), 4))

✅ Accuracy     : 0.8165
✅ Precision    : 0.8186
✅ Recall       : 0.7724
✅ F1 Score     : 0.7948
✅ ROC AUC Score: 0.8862
